### ISSUE TITLE
Was genau ist ein Kühlschrankverwaltung ?

### ISSUE THREAD

**Issue by BogusCurry** [tinabrunner/FreezerManagement#14]
Hallo ;D
Bin per Zufall auf dieses Projekt gestossen und bin ein wenig verwirrend bei dem Namen Kühlschrankverwaltung, was muss ich mir darunter vorstellen ?

Tschöö

Bogus

**Comment by phil294** [comment]
ja hallo na

das geht doch echt nicht an, dass dem lieben Bogus keiner antwortet. also unsere Kühlschrankverwaltung  entstand als Gruppenarbeit einer Vorlesung und ist eine Software, die aus Server und Website besteht. Da kannst du dann im Browser sehen, welche Produkte in deinem Kühlschrank sind und kannst automatisch Eier und Joghurt und so nachbestellen. wer das nutzt, dem ist auch nicht mehr weiterzuhelfen

 

Gesendet: Montag, 09. Januar 2017 um 20:26 Uhr
Von: "Bogus curry" <notifications@github.com>
An: tinabrunner/FreezerManagement <FreezerManagement@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [tinabrunner/FreezerManagement] Was genau ist ein Kühlschrankverwaltung ? (#14)


Hallo ;D
Bin per Zufall auf dieses Projekt gestossen und bin ein wenig verwirrend bei dem Namen Kühlschrankverwaltung, was muss ich mir darunter vorstellen ?

Tschöö

Bogus
